services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: commerce
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - commerce_pg_data:/var/lib/postgresql/data

volumes:
  commerce_pg_data:
